name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate that methods is atleast valid json
        run:  python -mjson.tool ./methods.json > /dev/null
